mcat = {'author':   "author=\"Your Name\",",
        'authmail': "author_email=\"your_address@domain.com\",",
        'callmain': "main()",
        'callstp':  "setup(name=\"PROJECT\"",
        'closep':   ")",
        'cmd':      "command not found",
        'cmdline':  "prog [-d] ARG ARG ...",
        'debug':    "-d      use the debugger",
        'defmn':    "def main:",
        'deftest':  "def test_function():",
        'describe': "Describe your project here",
        'dot_pt':   ".pytool",
        'empty':    "",
        'entpts':   "entry_points={'console_scripts': [proj = proj:main]}",
        'env':      "env",
        'flake':    "flake8 pytool test",
        'ifneqm':   "if __name__ == \"__main__\":",
        'indent':   "    ",
        'impdd':    "import docopt_dispatch",
        'imppytst': "import pytest",
        'impstp':   "from setuptools import setup",
        'impsys':   "import sys",
        'isfile':   "is a file, cannot mkdir",
        'lchome':   "home",
        'mbdir':    "$HOME must be a directory",
        'mbset':    "PYTOOL_DIR or HOME must be set",
        'mcom':     "main entrypoint",
        'newline':  "\n",
        'nosuch':   "No such file or directory",
        'notdir':   "is not a directory",
        'options':  "Options:",
        'please':   "Please set PYTOOL_DIR or HOME",
        'ptdir':    "PYTOOL_DIR",
        'pthelp':   "pytool --help",
        'ptini':    "pytool.ini",
        'skel':     "produce skeletons for python programs",
        'sqpt':     "[pytool]",
        'testdoc':  "Test function description",
        'title':    "# Project Title",
        'tmpldir':  "templates_dir",
        'trace':    "Traceback",
        'triquo':   "\"\"\"",
        'uchome':   "HOME",
        'usage':    "Usage:",
        'where':    "print(\"This is where your code goes\")",
        'writst':   "print(\"Put your test code here\")",
        }
